//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStatement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountStatement()
        {
            this.AccountStatementMasters = new HashSet<AccountStatementMaster>();
        }
    
        public string AccountTran { get; set; }
        public System.DateTime PostingDate { get; set; }
        public System.DateTime ValueDate { get; set; }
        public string Branch { get; set; }
        public string Descript { get; set; }
        public string RefChqN0 { get; set; }
        public decimal WithDrawals { get; set; }
        public decimal Deposit { get; set; }
        public decimal Balance { get; set; }
        public bool used { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountStatementMaster> AccountStatementMasters { get; set; }
    }
}
