//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStatementMaster
    {
        public string AccountNo { get; set; }
        public string AccountTran { get; set; }
    
        public virtual AccountStatement AccountStatement { get; set; }
    }
}
