//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStatementView
    {
        public string AccountTran { get; set; }
        public System.DateTime PostingDate { get; set; }
        public System.DateTime ValueDate { get; set; }
        public string Branch { get; set; }
        public string Descript { get; set; }
        public string RefChqN0 { get; set; }
        public decimal WithDrawals { get; set; }
        public decimal Deposit { get; set; }
        public decimal Balance { get; set; }
        public string AccountNo { get; set; }
        public bool used { get; set; }
    }
}
