//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountMaster()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
        }
    
        public string AccountNo { get; set; }
        public string InstId { get; set; }
        public string Name { get; set; }
        public string CustId { get; set; }
        public string CardNo { get; set; }
        public string Email { get; set; }
        public decimal Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
    }
}
