//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakUpTransaction
    {
        public string TransactionNo { get; set; }
        public int BreakUpNo { get; set; }
        public string VoucherNo { get; set; }
        public string CommitmentNo { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public decimal Amount { get; set; }
    }
}
