//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImprestEntities : DbContext
    {
        public ImprestEntities()
            : base("name=ImprestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountMaster> AccountMasters { get; set; }
        public virtual DbSet<AccountStatement> AccountStatements { get; set; }
        public virtual DbSet<AccountStatementMaster> AccountStatementMasters { get; set; }
        public virtual DbSet<AccountTransaction> AccountTransactions { get; set; }
        public virtual DbSet<BreakUpTransaction> BreakUpTransactions { get; set; }
        public virtual DbSet<BRSTransaction> BRSTransactions { get; set; }
        public virtual DbSet<ChequeNotDeposited> ChequeNotDepositeds { get; set; }
        public virtual DbSet<ChequeTransaction> ChequeTransactions { get; set; }
        public virtual DbSet<ClaimNotSubmittedTransaction> ClaimNotSubmittedTransactions { get; set; }
        public virtual DbSet<DeletedBreakUpNo> DeletedBreakUpNoes { get; set; }
        public virtual DbSet<DeletedTransactionNO> DeletedTransactionNOes { get; set; }
        public virtual DbSet<NarrationTransaction> NarrationTransactions { get; set; }
        public virtual DbSet<ProjectTransaction> ProjectTransactions { get; set; }
        public virtual DbSet<RecoupmentTransaction> RecoupmentTransactions { get; set; }
        public virtual DbSet<SupplierMaster> SupplierMasters { get; set; }
        public virtual DbSet<SupplierTransaction> SupplierTransactions { get; set; }
        public virtual DbSet<TransactionMaster> TransactionMasters { get; set; }
        public virtual DbSet<VoucherDateTransaction> VoucherDateTransactions { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<AccountStatementView> AccountStatementViews { get; set; }
        public virtual DbSet<TransactionReport> TransactionReports { get; set; }
        public virtual DbSet<OpenCloseBalance> OpenCloseBalances { get; set; }
        public virtual DbSet<ComputeOpenCloseBal> ComputeOpenCloseBals { get; set; }
    }
}
