//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenCloseBalance
    {
        public string AccountNo { get; set; }
        public System.DateTime TranDate { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal closingBalance { get; set; }
    }
}
