//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionMaster()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
            this.BRSTransactions = new HashSet<BRSTransaction>();
            this.ChequeNotDepositeds = new HashSet<ChequeNotDeposited>();
            this.ClaimNotSubmittedTransactions = new HashSet<ClaimNotSubmittedTransaction>();
            this.ProjectTransactions = new HashSet<ProjectTransaction>();
            this.VoucherDateTransactions = new HashSet<VoucherDateTransaction>();
        }
    
        public string TransactionNo { get; set; }
        public decimal Amount { get; set; }
        public bool credit { get; set; }
        public int voucherId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BRSTransaction> BRSTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeNotDeposited> ChequeNotDepositeds { get; set; }
        public virtual ChequeTransaction ChequeTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimNotSubmittedTransaction> ClaimNotSubmittedTransactions { get; set; }
        public virtual NarrationTransaction NarrationTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTransaction> ProjectTransactions { get; set; }
        public virtual RecoupmentTransaction RecoupmentTransaction { get; set; }
        public virtual SupplierTransaction SupplierTransaction { get; set; }
        public virtual VoucherType VoucherType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherDateTransaction> VoucherDateTransactions { get; set; }
    }
}
