//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace copyTallyToImprest.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDateTransaction
    {
        public string TransactionNo { get; set; }
        public System.DateTime VoucherDate { get; set; }
    
        public virtual TransactionMaster TransactionMaster { get; set; }
    }
}
